import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import CenteredTabs from '../components/Tabs'

const Home: NextPage = () => {
  return (
    <div className='flex flex-col h-screen'>
      <Head>
        <title>Movitun Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <CenteredTabs />
      <body className='h-full bg-[#EFF6F6]'>
        Hola Mundo
      </body>
      <Footer />
    </div>
  )
}

export default Home
